version: '3.9'

services:
  backend:
    image: kunikap/autotrack-backend:latest
    restart: unless-stopped
    volumes:
      - ./backend/.env:/app/backend/.env:ro
      - ./backend/data:/app/backend/data
      - uploads:/app/backend/uploads
      - paddleocr_cache:/root/.paddleocr
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    image: kunikap/autotrack-frontend:latest
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend

  watchtower:
    image: containrrr/watchtower:1.7.1
    restart: unless-stopped
    volumes:
      - //var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - DOCKER_API_VERSION=1.43

volumes:
  uploads:
  paddleocr_cache:
