# Called by the Inno Setup installer during post-install.
# Reads the RTSP URL from a temp file (avoids command-line escaping issues with
# special characters like @ : / in camera URLs), generates a secure JWT secret,
# and writes backend/.env into the install directory.

param([string]$InstallDir)

# Read RTSP URL written by Pascal before calling this script
$rtspFile = Join-Path $env:TEMP "autotrack_rtsp.txt"
$rtspUrl  = ""
if (Test-Path $rtspFile) {
    $rtspUrl = (Get-Content $rtspFile -Raw -Encoding UTF8).Trim()
    Remove-Item $rtspFile -Force -ErrorAction SilentlyContinue
}

# Cryptographically secure 64-character hex secret
$bytes  = [System.Security.Cryptography.RandomNumberGenerator]::GetBytes(32)
$secret = [BitConverter]::ToString($bytes) -replace '-', ''

$envContent = @"
# AutoTrack Branch Configuration
# Generated by installer on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')
# Edit this file to change settings, then run: docker compose restart backend

JWT_SECRET_KEY=$secret

# RTSP camera URL — can also be changed later from the app Settings menu
RTSP_URL=$rtspUrl

# CORS — keep as-is for a standard local installation
ALLOWED_ORIGINS=http://localhost,http://localhost:5173,http://localhost:4173

LOG_LEVEL=INFO
IMAGE_RETENTION_DAYS=30

# Cloud image storage (optional — leave blank to store images on this PC)
S3_ENDPOINT_URL=
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET_NAME=autotrack-images
S3_PUBLIC_URL=

# Error tracking (optional — set to a Sentry DSN to enable)
SENTRY_DSN=
"@

$backendDir = Join-Path $InstallDir "backend"
if (-not (Test-Path $backendDir)) {
    New-Item -ItemType Directory -Path $backendDir -Force | Out-Null
}

$envPath = Join-Path $backendDir ".env"
Set-Content -Path $envPath -Value $envContent -Encoding UTF8
Write-Host "Written: $envPath"
